'use client';

import React from 'react';
import {
  Activity,
  CheckCircle,
  AlertTriangle,
  AlertCircle,
  Download,
  Share2,
  RefreshCw,
  ChevronDown,
  ChevronUp,
  Stethoscope,
  Heart,
  Shield,
} from 'lucide-react';
import type {
  DiseasePredictionResult,
  SingleDiseasePrediction,
  RiskLevel,
  DiseaseType,
} from '@/types/disease-prediction';
import { DISEASE_INFO, RISK_LEVEL_STYLES, RISK_LEVEL_EMOJI } from '@/types/disease-prediction';

interface DiseasePredictionResultsProps {
  result: DiseasePredictionResult;
  petName?: string;
  onNewAnalysis: () => void;
  onClose: () => void;
}

export default function DiseasePredictionResults({
  result,
  petName,
  onNewAnalysis,
  onClose,
}: DiseasePredictionResultsProps) {
  const [expandedDisease, setExpandedDisease] = React.useState<string | null>(null);

  const getRiskIcon = (riskLevel: RiskLevel) => {
    switch (riskLevel) {
      case 'High':
        return <AlertCircle className="w-5 h-5 text-red-600" />;
      case 'Moderate':
        return <AlertTriangle className="w-5 h-5 text-yellow-600" />;
      case 'Low':
        return <CheckCircle className="w-5 h-5 text-green-600" />;
    }
  };

  const getProgressBarColor = (probability: number) => {
    if (probability >= 60) return 'bg-red-500';
    if (probability >= 30) return 'bg-yellow-500';
    return 'bg-green-500';
  };

  const toggleExpand = (disease: string) => {
    setExpandedDisease(expandedDisease === disease ? null : disease);
  };

  const handleDownloadReport = () => {
    // Generate a text report
    const report = `
MULTI-DISEASE RISK ASSESSMENT REPORT
=====================================
${petName ? `Pet: ${petName}` : ''}
Date: ${new Date(result.analyzed_at).toLocaleString()}

PET PROFILE
-----------
Age Group: ${result.pet_profile.age_group}
Weight Status: ${result.pet_profile.weight_status}
Risk Factors: ${result.pet_profile.risk_factors_count}

OVERALL ASSESSMENT
------------------
Has Risk: ${result.has_risk ? 'Yes' : 'No'}
${result.highest_risk_disease ? `Highest Risk: ${result.highest_risk_disease}` : ''}

DISEASE PREDICTIONS
-------------------
${result.predictions.map(p => `
${p.disease}
  - Probability: ${p.probability.toFixed(1)}%
  - Risk Level: ${p.risk_level}
  - Status: ${p.is_positive ? 'POSITIVE' : 'Negative'}
  - Key Indicators: ${p.key_indicators.join(', ') || 'None'}
`).join('\n')}

RECOMMENDATIONS
---------------
${result.recommendations.map((r, i) => `${i + 1}. ${r}`).join('\n')}

=====================================
This report is generated by VetLink AI Disease Prediction System.
Please consult a veterinarian for professional medical advice.
    `.trim();

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `disease-report-${petName || 'pet'}-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-white rounded-2xl shadow-xl border border-gray-200 overflow-hidden">
      {/* Header */}
      <div className="bg-gradient-to-r from-purple-600 to-indigo-700 px-6 py-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 bg-white/20 rounded-xl flex items-center justify-center">
              <Stethoscope className="w-7 h-7 text-white" />
            </div>
            <div>
              <h2 className="text-2xl font-bold text-white">
                🔬 Disease Risk Analysis Complete
              </h2>
              <p className="text-purple-100 text-sm">
                {petName ? `Results for ${petName}` : 'Multi-disease risk assessment results'}
              </p>
            </div>
          </div>
          <p className="text-white/80 text-sm">
            {new Date(result.analyzed_at).toLocaleString()}
          </p>
        </div>
      </div>

      <div className="p-6 space-y-6">
        {/* Overall Summary */}
        <div className={`p-6 rounded-xl border-2 ${
          result.has_risk
            ? 'bg-gradient-to-br from-red-50 to-orange-50 border-red-200'
            : 'bg-gradient-to-br from-green-50 to-emerald-50 border-green-200'
        }`}>
          <div className="flex items-start justify-between">
            <div>
              <div className="flex items-center gap-2 mb-2">
                {result.has_risk ? (
                  <AlertTriangle className="w-6 h-6 text-red-600" />
                ) : (
                  <Heart className="w-6 h-6 text-green-600" />
                )}
                <h3 className="text-xl font-bold text-gray-900">
                  {result.has_risk ? 'Health Risks Detected' : 'No Significant Risks'}
                </h3>
              </div>
              {result.highest_risk_disease && result.has_risk && (
                <p className="text-gray-700">
                  <span className="font-semibold">Highest concern:</span>{' '}
                  <span className="text-red-700 font-bold">{result.highest_risk_disease}</span>
                </p>
              )}
            </div>
            <div className="text-right">
              <div className="flex items-center gap-4">
                <div className="text-center">
                  <p className="text-xs text-gray-500 uppercase">Age Group</p>
                  <p className="font-bold text-gray-900">{result.pet_profile.age_group}</p>
                </div>
                <div className="text-center">
                  <p className="text-xs text-gray-500 uppercase">Weight Status</p>
                  <p className="font-bold text-gray-900">{result.pet_profile.weight_status}</p>
                </div>
                <div className="text-center">
                  <p className="text-xs text-gray-500 uppercase">Risk Factors</p>
                  <p className={`font-bold ${
                    result.pet_profile.risk_factors_count >= 5
                      ? 'text-red-600'
                      : result.pet_profile.risk_factors_count >= 3
                        ? 'text-yellow-600'
                        : 'text-green-600'
                  }`}>
                    {result.pet_profile.risk_factors_count}
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Disease Predictions Grid */}
        <div>
          <h3 className="text-lg font-bold text-gray-900 mb-4 flex items-center gap-2">
            📊 Disease Risk Assessment ({result.predictions.length} conditions analyzed)
          </h3>

          <div className="space-y-3">
            {result.predictions.map((prediction) => {
              const diseaseInfo = DISEASE_INFO[prediction.disease];
              const riskStyles = RISK_LEVEL_STYLES[prediction.risk_level];
              const isExpanded = expandedDisease === prediction.disease;

              return (
                <div
                  key={prediction.disease}
                  className={`border-2 rounded-xl overflow-hidden transition-all ${
                    prediction.is_positive && prediction.disease !== 'Healthy'
                      ? riskStyles.border
                      : 'border-gray-200'
                  }`}
                >
                  {/* Disease Header */}
                  <button
                    type="button"
                    onClick={() => toggleExpand(prediction.disease)}
                    className={`w-full p-4 flex items-center justify-between ${
                      prediction.is_positive && prediction.disease !== 'Healthy'
                        ? riskStyles.bg
                        : 'bg-gray-50 hover:bg-gray-100'
                    } transition-colors`}
                  >
                    <div className="flex items-center gap-3">
                      <span className="text-2xl">{diseaseInfo?.icon || '🔬'}</span>
                      <div className="text-left">
                        <p className="font-bold text-gray-900">{prediction.disease}</p>
                        <p className="text-sm text-gray-600">{diseaseInfo?.description || ''}</p>
                      </div>
                    </div>

                    <div className="flex items-center gap-4">
                      {/* Probability */}
                      <div className="text-right">
                        <p className="text-2xl font-bold text-gray-900">
                          {prediction.probability.toFixed(0)}%
                        </p>
                        <p className="text-xs text-gray-500">probability</p>
                      </div>

                      {/* Risk Badge */}
                      <div className={`px-3 py-1.5 rounded-lg font-bold flex items-center gap-1.5 ${
                        riskStyles.bg} ${riskStyles.text}`}>
                        <span>{RISK_LEVEL_EMOJI[prediction.risk_level]}</span>
                        <span>{prediction.risk_level}</span>
                      </div>

                      {/* Status Badge */}
                      {prediction.is_positive && prediction.disease !== 'Healthy' && (
                        <span className="px-3 py-1.5 bg-red-600 text-white rounded-lg font-bold text-sm">
                          POSITIVE
                        </span>
                      )}

                      {/* Expand Icon */}
                      {isExpanded ? (
                        <ChevronUp className="w-5 h-5 text-gray-500" />
                      ) : (
                        <ChevronDown className="w-5 h-5 text-gray-500" />
                      )}
                    </div>
                  </button>

                  {/* Expanded Content */}
                  {isExpanded && (
                    <div className="p-4 border-t border-gray-200 bg-white">
                      {/* Progress Bar */}
                      <div className="mb-4">
                        <div className="flex justify-between text-sm mb-1">
                          <span className="text-gray-600">Risk Probability</span>
                          <span className="font-semibold">{prediction.probability.toFixed(1)}%</span>
                        </div>
                        <div className="w-full h-3 bg-gray-200 rounded-full overflow-hidden">
                          <div
                            className={`h-full transition-all duration-500 ${getProgressBarColor(prediction.probability)}`}
                            style={{ width: `${prediction.probability}%` }}
                          />
                        </div>
                        <div className="flex justify-between text-xs text-gray-500 mt-1">
                          <span>Low (0-30%)</span>
                          <span>Moderate (30-60%)</span>
                          <span>High (60-100%)</span>
                        </div>
                      </div>

                      {/* Key Indicators */}
                      {prediction.key_indicators.length > 0 && (
                        <div>
                          <p className="text-sm font-semibold text-gray-700 mb-2">
                            Key Risk Indicators:
                          </p>
                          <ul className="space-y-1">
                            {prediction.key_indicators.map((indicator, idx) => (
                              <li key={idx} className="flex items-center gap-2 text-sm text-gray-600">
                                <span className="w-1.5 h-1.5 rounded-full bg-gray-400" />
                                {indicator}
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>

        {/* Recommendations */}
        <div className="bg-gradient-to-br from-blue-50 to-indigo-50 rounded-xl p-6 border-2 border-blue-200">
          <h3 className="text-lg font-bold text-gray-900 mb-4 flex items-center gap-2">
            <Shield className="w-5 h-5 text-blue-600" />
            💡 Veterinary Recommendations
          </h3>
          <ul className="space-y-3">
            {result.recommendations.map((rec, idx) => (
              <li key={idx} className="flex items-start gap-3">
                <CheckCircle className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5" />
                <span className="text-gray-700">{rec}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Disclaimer */}
        <div className="p-4 bg-amber-50 border border-amber-200 rounded-xl">
          <div className="flex items-start gap-3">
            <AlertTriangle className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" />
            <div className="text-sm text-amber-800">
              <strong>Important Disclaimer:</strong> This AI-powered analysis is for informational purposes only 
              and should not replace professional veterinary diagnosis. Please consult a licensed veterinarian 
              for proper medical evaluation and treatment.
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 pt-4 border-t border-gray-200">
          <button
            onClick={handleDownloadReport}
            className="px-6 py-3 bg-blue-600 text-white rounded-xl font-semibold hover:bg-blue-700 transition-colors flex items-center justify-center gap-2"
          >
            <Download className="w-5 h-5" />
            Download Report
          </button>
          <button
            onClick={onNewAnalysis}
            className="px-6 py-3 bg-purple-600 text-white rounded-xl font-semibold hover:bg-purple-700 transition-colors flex items-center justify-center gap-2"
          >
            <RefreshCw className="w-5 h-5" />
            New Analysis
          </button>
          <button
            onClick={onClose}
            className="px-6 py-3 border-2 border-gray-300 text-gray-700 rounded-xl font-semibold hover:bg-gray-50 transition-colors flex items-center justify-center gap-2"
          >
            Back to BCS
          </button>
        </div>
      </div>
    </div>
  );
}
