#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Pre-commit hook - no restrictions
# Commits are allowed with any commit message
# Only pushing to main is restricted (see pre-push hook)

exit 0
